version: "3.5"

services:
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: ca
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    
